[WIP] Visitor can view all listed articles
CraftAcademy/the_sunrise_press pull request #25
Opened 2019-01-18 11:57 UTC by Bovverskin

## Pivotal Tracker
https://www.pivotaltracker.com/story/show/163088245

## Tasks
- Add to feature test to include language option

## Gems

## Description/User Story
As a user
In order to be able to read articles in my native language,
I would like to switch between languages English and Swedish

2019-01-19 15:08 UTC, CamronLDNF approved these changes
Looks good to me. Go ahead.

2019-01-20 06:56 UTC, johannaanden approved these changes
LGTM

2019-01-21 08:26 UTC, oliverochman requested changes

2019-01-21 08:26 UTC, oliverochman commented on app/views/partials/_category_navbar.html.haml
> +                = link_to t(category.name), category_path(category), class: 'category-item'
is the "t" in `t(category.name)` a typo?

2019-01-21 08:26 UTC, oliverochman commented on features/visitor_can_view_all_listed_articles.feature
> +        And I should see 'News'
You need to have a "Then" here

2019-01-21 08:32 UTC, Bovverskin commented on app/views/partials/_category_navbar.html.haml
> +                = link_to t(category.name), category_path(category), class: 'category-item'
No.  We need this for changing the language to Swedish.

2019-01-21 08:33 UTC, Bovverskin commented on features/visitor_can_view_all_listed_articles.feature
> +        And I should see 'News'
This has been fixed.

2019-01-21 08:43 UTC, oliverochman commented on app/views/partials/_category_navbar.html.haml
> +                = link_to t(category.name), category_path(category), class: 'category-item'
Okay, thanks for the reply

2019-01-21 08:46 UTC, oliverochman approved these changes

2019-01-21 08:46 UTC, merged